# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a4af824fd09062fb8bb5034ca64b679d97e7371541defa324c07195381daf516625c208d39514fe6cc3038676b56d2cf3e96ce539da301b8f765e0659f720f6

test:
  secret_key_base: 744a9c5d39f1d5137bc9a2c9bc656246f6f9ce04dc19da1bbe4aa22536bcc6531552b1b5d0c3af97a969d8d823e8a6df304033c8c0c0e5b836e34d7be1920ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
